# Generated by Django 3.2.7 on 2021-12-02 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdPict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(upload_to='static/img')),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='odflghfhgkdfjgdf',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Naming', models.CharField(blank=True, max_length=200, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('Pics', models.ManyToManyField(blank=True, null=True, to='mainApp.ProdPict')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProdList', models.ManyToManyField(blank=True, null=True, to='mainApp.Product')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
