# Generated by Django 3.2.7 on 2021-12-05 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20211202_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ProdList',
            field=models.ManyToManyField(blank=True, to='mainApp.Product'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='Pics',
        ),
        migrations.AddField(
            model_name='product',
            name='Pics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.prodpict'),
        ),
    ]
